title = "Log scrubber example config"

[[directory]]
name = "Apache Logs"
path = "/tmp/files/*/*/*"
exclude = ["zip"]
keep_latest = 10

    [[directory.strategy]]
    type = "size"
    action = "delete"
    limit = "1b"

