title = "Log scrubber example config"

[[directory]]
name = "Apache Logs"
path = "/var/log/apache"
keep_latest = 10

    [[directory.strategy]]
    type = "age"
    action = "delete"
    limit = "30d"

