project_name: scrubber
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w 
    goos:
      - linux
      - windows
#      - darwin
    main: ./cmd/scrubber
    binary: scrubber
nfpms:
  - package_name: scrubber
    maintainer: Tobias Kuendig <tobias@offline.ch>
    description: Scrubber provides an easy way to clean up old files in a directory.
    formats:
      - deb
      - rpm
    license: MIT
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}_binary"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
